---
- hosts: jenkins
  become: true
  vars:
      java_packages: #@ disable if host is RedHat
          - openjdk-17-jdk #? jenkins require java >=17
  roles:
      - role: geerlingguy.java
      - role: geerlingguy.jenkins

- hosts: jenkins
  become: yes
  roles:
      - geerlingguy.nginx
  tags:
      - proxy
  vars:
      #@ custom----------------------------------------------------------------
      nginx_vhosts:
          #~ JENKINS ------------------------------------------------------
          - listen: '80'
            server_name: 'jenkins.local'
            return: '301 https://jenkins.local$request_uri'
            filename: 'jenkins80.local.conf'

          - listen: '443 ssl'
            http2: 'on'
            server_name: 'jenkins.local'
            # server_name_redirect: 'jenkins.local'
            # root: '/var/www/example.com'
            # index: 'index.php index.html index.htm'
            # error_page: ''
            # access_log: ''
            # error_log: ''
            access_log: '/var/log/nginx/jenkins.access.log'
            error_log: '/var/log/nginx/jenkins.error.log'
            state: 'present' #? make sure this is existing, if existing it skip override
            #   template: '{{ nginx_vhost_template }}' #? specify template to pass these objects to there
            filename: 'jenkins443.local.conf' #? name of this config
            extra_parameters: |
                ssl_certificate     /etc/nginx/ssl/jenkins.local.crt;
                ssl_certificate_key /etc/nginx/ssl/jenkins.local.key;
                ssl_protocols       TLSv1.1 TLSv1.2;
                ssl_ciphers         HIGH:!aNULL:!MD5;
                location / {
                    proxy_pass http://jenkins;
                    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
                    proxy_redirect off;

                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto https;
                }
            #* jenkins end------------------------------------------------------
      nginx_upstreams:
          - name: jenkins
            servers:
                - 'localhost:8080'
