{
 "title": "Docker Swarm Dashboard",
 "description": "Docker Swarm stacks and services metrics",
 "tags": [ "swarmprom" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm Node", "query": "node_meta" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "stack_namespace",
    "label": "Stack",
    "query": "query_result(count(container_last_seen{container_label_com_docker_stack_namespace=~\".+\"}) by (container_label_com_docker_stack_namespace))"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(node_load1)" }
   ]
  },
  {
   "title": "Stacks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[5m])) "
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Available CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) * 100 / count(node_cpu_seconds_total{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{device=\"rootfs\", mountpoint=\"/\"} / node_filesystem_size_bytes{device=\"rootfs\", =\"/\"}) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{device=\"rootfs\", mountpoint=\"/\"} - node_filesystem_avail_bytes{device=\"rootfs\", mountpoint=\"/\"})* on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})",
     "legendFormat": "{{ Disk Usage in GB }}"
    }
   ]
  },
  {
   "title": "Service Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_stack_namespace=~\"$stack_namespace\",container_label_com_docker_swarm_node_id=~\"$node_id\"}[5m])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Containers # (by Service type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$interval])) by (container_label_com_docker_stack_namespace)",
     "legendFormat": "{{container_label_com_docker_stack_namespace}}"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[1m])) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[$interval])) by (name)) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Used {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "sum(container_memory_cache{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Cached {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Memory usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg_over_time(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[$interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic on Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$interval]) )",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$interval])) ",
     "legendFormat": "Writes "
    }
   ]
  },
  {
   "title": "Network received by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network transmitted by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}