---
#@ custom
# nfs_exports: []
nfs_exports:
    ['/data/nfs_export 192.168.140.0/24(rw,sync,no_root_squash,no_all_squash,no_subtree_check)']
#@ ----------------------------------------------------------------

nfs_rpcbind_state: started
nfs_rpcbind_enabled: true
