Vagrant.configure(2) do |config|

	#* Set some variables
  etcHosts=""
  common = <<-SHELL
  sudo apt update -qq 2>&1 >/dev/null
  sudo apt install -y -qq git vim tree net-tools telnet git python3-pip sshpass nfs-common 2>&1 >/dev/null
  sudo echo "autocmd filetype yaml setlocal ai ts=2 sw=2 et" > /home/vagrant/.vimrc
  #/ SSH require enter yes/no for first time login
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sudo systemctl restart sshd
  SHELL

	#/ set vagrant image
	config.vm.box = "ubuntu/focal64"
	config.vm.box_url = "ubuntu/focal64"

	#/ set servers list and their parameters
	NODES = [
  	{ :hostname => "master1", :ip => "192.168.140.10", :cpus => 2, :mem => 3072 },
  	{ :hostname => "worker1", :ip => "192.168.140.21", :cpus => 2, :mem => 2048 },
  	{ :hostname => "worker2", :ip => "192.168.140.22", :cpus => 2, :mem => 2048 },
  	# { :hostname => "node4", :ip => "192.168.140.13", :cpus => 2, :mem => 2048 },
  	# { :hostname => "node5", :ip => "192.168.140.14", :cpus => 2, :mem => 2048 },
  	# { :hostname => "node6", :ip => "192.168.140.15", :cpus => 2, :mem => 2048 },
  	# { :hostname => "node7", :ip => "192.168.140.16", :cpus => 2, :mem => 2048 }
	]


	#* define /etc/hosts for all servers
  NODES.each do |node|
   	etcHosts += "echo '" + node[:ip] + "   " + node[:hostname] + "' >> /etc/hosts" + "\n"
  end

	# run installation
  NODES.each do |node|
    config.vm.define node[:hostname] do |cfg|
			cfg.vm.hostname = node[:hostname]
      cfg.vm.network "private_network", ip: node[:ip]
      cfg.vm.provider "virtualbox" do |v|
				v.customize [ "modifyvm", :id, "--cpus", node[:cpus] ]
        v.customize [ "modifyvm", :id, "--memory", node[:mem] ]
        #/ cho phép máy ảo sử dụng máy chủ DNS của host.
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #/ cho phép máy ảo sử dụng proxy DNS của host.
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--name", node[:hostname] ]
      end #/ end provider

			#/ for all
      #/ :inline được sử dụng để nhúng trực tiếp các lệnh shell vào trong Vagrantfile.
      cfg.vm.provision :shell, :inline => etcHosts
      cfg.vm.provision :shell, :inline => common

    end #/ end config
  end #/ end nodes
end
