---
- name: restart gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when | bool

- name: restart nginx
  command: gitlab-ctl restart nginx
